type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Alter Warehouse"
      parameters:
        componentName: "Start"
    Alter Warehouse:
      type: "alter-warehouse"
      transitions:
        success:
        - "Alter Warehouse 2"
      parameters:
        componentName: "Alter Warehouse"
        warehouse: "[Environment Default]"
        commandType: "Resume"
    Alter Warehouse 2:
      type: "alter-warehouse"
      parameters:
        componentName: "Alter Warehouse 2"
        warehouse: "[Environment Default]"
        commandType: "Suspend"

